name: Agent Approval Request
description: Request approval for a new automation agent to commit to this repository
title: "[Agent Request] "
labels: ["agent-approval", "governance"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Agent Approval Request
        
        Use this template to request approval for a new automation agent that will create commits in this repository.
        
        All commits must be from approved agents as per our agent-only commit policy.

  - type: input
    id: agent-username
    attributes:
      label: Agent Username
      description: The exact GitHub username that will appear in commits
      placeholder: "my-bot[bot]"
    validations:
      required: true

  - type: dropdown
    id: agent-type
    attributes:
      label: Agent Type
      description: What type of agent is this?
      options:
        - GitHub App
        - Bot User
        - Service Account
        - GitHub Action
        - Other
    validations:
      required: true

  - type: input
    id: app-id
    attributes:
      label: GitHub App ID
      description: If this is a GitHub App, provide the App ID (optional)
      placeholder: "123456"
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What will this agent be used for?
      placeholder: |
        - Automated dependency updates
        - Code generation for feature X
        - Scheduled maintenance tasks
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Why is this agent needed? What problem does it solve?
      placeholder: Explain why existing approved agents cannot handle this use case
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Expected Commit Frequency
      description: How often will this agent create commits?
      options:
        - Multiple times per day
        - Daily
        - Weekly
        - Monthly
        - On-demand/As needed
    validations:
      required: true

  - type: input
    id: owner
    attributes:
      label: Agent Owner
      description: Who is responsible for maintaining this agent?
      placeholder: "@username or team-name"
    validations:
      required: true

  - type: textarea
    id: security
    attributes:
      label: Security Considerations
      description: |
        Describe any security measures in place:
        - Authentication method
        - Credential storage
        - Access controls
        - Monitoring/logging
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have tested this agent in a fork or test environment
          required: true
        - label: I have reviewed the agent setup documentation
          required: true
        - label: I understand this agent will be subject to audit and monitoring
          required: true
        - label: I will maintain this agent and respond to any issues
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Next Steps
        
        After submitting:
        1. A repository administrator will review your request
        2. You may be asked for additional information
        3. If approved, the agent will be added to `.github/approved-agents.json`
        4. You will be notified when the agent is ready to use
        
        For questions, see [Agent Setup Guide](how-we-work/agent-setup.md)
