name: Bug Report
description: Report a defect or broken functionality
title: "[Bug]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Template
        Use this template to report defects, broken functionality, or unexpected behavior.
        
        **Before reporting a bug:**
        - Search existing issues to avoid duplicates
        - Verify the behavior is actually a bug (not expected behavior)
        - Gather all necessary information to reproduce

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: A clear, concise summary of the bug (will be prefixed with [Bug]:)
      placeholder: "Example: Template validation fails for valid issue numbers"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - "Critical - System is unusable or data loss"
        - "High - Major functionality is broken"
        - "Medium - Feature doesn't work as expected"
        - "Low - Minor issue or cosmetic problem"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe the bug in detail. What is happening? What should happen instead?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug
      placeholder: |
        Please provide step-by-step instructions:
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened, including any error messages
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
        - Browser: [e.g., Chrome 120, Firefox 121] (if applicable)
        - Version: [e.g., v1.2.3]
        - Other relevant details
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: Add screenshots, error logs, or other supporting information
      placeholder: |
        Paste screenshots or logs here.
        You can drag and drop images directly into this field.
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Is there a temporary workaround for this issue?
      placeholder: Describe any workaround you've found
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Include any other relevant information, related issues, or context
    validations:
      required: false
